---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  UNSPLASH_SECRETS_KEY: <unsplash key>
  API_HOST: http://localhost:9090
  REDISCLOUD_URL: <url-assigned-by-Redis-provider-on-Heroku>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  FAVORITE_QUEUE: lightofday-dev
  FAVORITE_QUEUE_URL: <set by AWS>
  SUBSCRIBE_QUEUE: lightofday-subscribe
  SUBSCRIBE_QUEUE_URL: <set by AWS>

test:
  DB_FILENAME: db/local/test.db
  UNSPLASH_SECRETS_KEY: <unsplash key>
  API_HOST: http://localhost:9090
  REDISCLOUD_URL: <url-assigned-by-Redis-provider-on-Heroku>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  FAVORITE_QUEUE: lightofday-test
  FAVORITE_QUEUE_URL: <set by AWS>
  SUBSCRIBE_QUEUE: lightofday-subscribe
  SUBSCRIBE_QUEUE_URL: <set by AWS>

production:
  # - assign DATABASE_URL in production
  UNSPLASH_SECRETS_KEY: <unsplash key>
  API_HOST: http://localhost:9090
  REDISCLOUD_URL: <url-assigned-by-Redis-provider-on-Heroku>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  FAVORITE_QUEUE: lightofday-production
  FAVORITE_QUEUE_URL: <set by AWS>
  SUBSCRIBE_QUEUE: lightofday-subscribe
  SUBSCRIBE_QUEUE_URL: <set by AWS>